export const products = {
  Vegetables: [
    {
      id: 1,
      name: "Potato (Aloo)",
      price: 28,
      originalPrice: 33,
      discount: 8,
      image: "/images/patato.png",
      weights: ["500 gm", "1 kg", "2 kg"],
      defaultWeight: "1 kg",
    },
    {
      id: 2,
      name: "Tomato (Tamatar)",
      price: 35,
      originalPrice: 40,
      discount: 8,
      image: "/images/tamato.png",
      weights: ["500 gm", "1 kg"],
      defaultWeight: "500 gm",
    },
    // Add more vegetables...
  ],
  Fruits: [
    {
      id: 1,
      name: "Apple",
      price: 28,
      originalPrice: 33,
      discount: 8,
      image: "/images/onion.png",
      weights: ["500 gm", "1 kg", "2 kg"],
      defaultWeight: "1 kg",
    },
    {
      id: 2,
      name: "Banana",
      price: 35,
      originalPrice: 40,
      discount: 8,
      image: "/images/redchilli.png",
      weights: ["500 gm", "1 kg"],
      defaultWeight: "500 gm",
    },
  ],
  Dairy: [
    {
      id: 1,
      name: "Milk",
      price: 28,
      originalPrice: 33,
      discount: 8,
      image: "/images/onion.png",
      weights: ["500 ml", "1 L", "2 L"],
      defaultWeight: "1 L",
    },
    {
      id: 2,
      name: "Cheese",
      price: 35,
      originalPrice: 40,
      discount: 8,
      image: "/images/redchilli.png",
      weights: ["200 gm", "500 gm"],
      defaultWeight: "200 gm",
    },
  ],
};
